/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.sapient.fee.calc;

import org.junit.Test;

import com.sapient.FeeCalculator;

import static org.junit.Assert.*;

public class FeeCalculatorTest {
    @Test public void testSomeLibraryMethod() {
        FeeCalculator classUnderTest = new FeeCalculator();
        assertTrue("someLibraryMethod should return 'true'", Boolean.TRUE);
    }
}
