/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.sapient;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.ConfigurableApplicationContext;

import com.sapient.fee.calc.facade.FeeCalculatorFacade;


@SpringBootApplication
public class FeeCalculator {
	
	
	public static void main(String args[]) {
		ConfigurableApplicationContext ctx =  SpringApplication.run(FeeCalculator.class, args);
		FeeCalculatorFacade client = ctx.getBean(FeeCalculatorFacade.class);
		client.processTransaction();
		
	}
	
	
}
